### ISSUE TITLE
Release message pkgs into Melodic and Noetic

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/abb_robot_driver_interfaces#2]
As these are standard ROS 1 message packages, they can be released via the ROS buildfarm.

We should do that, as it will remove the need to build those packages from source in a Catkin workspace.

**Comment by gavanderhoorn** [comment]
@jontje: I plan to find some time to do this next week.

Let me know if you see any reason to delay releasing these packages.

**Comment by jontje** [comment]
> @jontje: I plan to find some time to do this next week.
> 
> Let me know if you see any reason to delay releasing these packages

I can't think of any reason to delay.

**Comment by gavanderhoorn** [comment]
Released into:

 - Kinetic: https://github.com/ros/rosdistro/pull/28935
 - Melodic: https://github.com/ros/rosdistro/pull/28936
 - Noetic: https://github.com/ros/rosdistro/pull/28937

Same version in all distros.

Kinetic is almost EOL, but it doesn't hurt to release the messages there as well.

At the very least it would make interacting with the driver easier from a Kinetic install (I know a few people still using that version), as they don't have to build anything from source then (note: *interacting* with the driver running somewhere else, not running it *on* Kinetic).

**Comment by gavanderhoorn** [comment]
Kinetic has been synced (ie: packages can now be installed using `apt`). Melodic and Noetic will be synced later.

As I don't expect any problems, I'm going to close the issue.

**Comment by gavanderhoorn** [comment]
With the merge of https://github.com/ros-industrial/abb_robot_driver/pull/25, we're now building `abb_robot_driver` with the released msg packages instead of a full source build.
